 // DO NOT TOUCH THIS FILE, AUTO GENERATED BY SYSTEM
//    Copyright
    import {AppOpFnMapType} from './d_meta';
    
   export  let AppOptFnMap:AppOpFnMapType ={
CSSBeautify:({Dot})=>{
            return {
                        optName: Dot("Ol1ZcWomT", "{0} Beautify", "CSS"),
            }
        },
CSSMinify:({Dot})=>{
            return {
                  optName: Dot("-nL_B5PoN", "Compresses {0}", "CSS"),
            }
        },
CSVToJSON:({Dot})=>{
            return {
                  optName: Dot("tZINaUR4b", "CSV to JSON"),
            }
        },
FromBase32:({Dot})=>{
            return {
                        optName: Dot("rVdu", "Decode {0}", "Base32"),
            }
        },
FromBase45:({Dot})=>{
            return {
                        optName: Dot("rVqlu", "Decode {0}", "Base45"),
            }
        },
FromBase58:({Dot})=>{
            return {
                        optName: Dot("L9qbQku", "Decode {0}", "Base58"),
            }
        },
FromBase62:({Dot})=>{
            return {
                        optName: Dot("L9bQku", "Decode {0}", "Base62"),
            }
        },
FromBase64:({Dot})=>{
            return {
                  optName: Dot("rVqlu", "Decode {0}", "Base64"),
            }
        },
FromBase85:({Dot})=>{
            return {
                        optName: Dot("rVqlu", "Decode {0}", "Base85"),
            }
        },
FromBCD:({Dot})=>{
            return {
                  optName: "From BCD",
            }
        },
FromHex:({Dot})=>{
            return {
                  optName: Dot("5RPdtVff3", "From Hex"),
            }
        },
GenericCodeBeautify:({Dot})=>{
            return {
                        optName: Dot("generic-NI-UFPTe0", "Beautify Generic Code"),
            }
        },
HTMLBeautify:({Dot})=>{
            return {
                        optName: Dot("yMZW-figFKwrYO", "Format HTML"),
            }
        },
JavaScriptBeautify:({Dot})=>{
            return {
                        optName: Dot("6UICxHzVR.name", "Beautify {0}", "JavaScript"),
            }
        },
JavaScriptMinify:({Dot})=>{
            return {
                  optName: Dot("e3WgQaZlb", "Compresses {0}", "JavaScript"),
            }
        },
JSONBeautify:({Dot})=>{
            return {
                        optName: Dot("json-beautify.text.93kq", "Beautify JSON Data"),
            }
        },
JSONMinify:({Dot})=>{
            return {
                  optName: Dot("meeMC1Uk7.text.93kq", "Minify {0}", "JSON"),
            }
        },
MD2:({Dot})=>{
            return {
                  optName: Dot("md2.text.192d3", "Generate {0} Hash", "MD2"),
            }
        },
MD4:({Dot})=>{
            return {
                  optName: Dot("md4.text.192d3", "Generate {0} Hash", "MD4"),
            }
        },
MD5:({Dot})=>{
            return {
                  optName: Dot("md5.textiDjMIo", "Generate {0} Hash", "MD5"),
            }
        },
MD6:({Dot})=>{
            return {
                  optName: Dot("md6.text.192d3", "Generate {0} Hash", "MD6"),
            }
        },
RemoveLineNumbers:({Dot})=>{
            return {
                  optName: Dot("OrCD8PqwH", "Remove line numbers"),
            }
        },
RemoveWhitespace:({Dot})=>{
            return {
                  optName: Dot("U-SKci0LP", "Remove whitespace"),
            }
        },
Reverse:({Dot})=>{
            return {
                  optName: "Reverse",
            }
        },
SHA0:({Dot})=>{
            return {
                  optName: "SHA0",
            }
        },
SHA1:({Dot})=>{
            return {
                  optName: "SHA1",
            }
        },
SHA2:({Dot})=>{
            return {
                  optName: "SHA2",
            }
        },
SHA3:({Dot})=>{
            return {
                  optName: "SHA3",
            }
        },
SQLBeautify:({Dot})=>{
            return {
                        optName: Dot("json-beautify.name.0912", "Format SQL"),
            }
        },
SQLMinify:({Dot})=>{
            return {
                  optName: Dot("6wdtJ4vmg.name.0912", "Minify {0}", "SQL"),
            }
        },
Tail:({Dot})=>{
            return {
                  optName: Dot("y46w7Q9TH", "Tail"),
            }
        },
ToBase32:({Dot})=>{
            return {
                        optName: Dot("M3ytc", "Encode {0}", "Base32"),
            }
        },
ToBase45:({Dot})=>{
            return {
                        optName: Dot("M3ytc", "Encode {0}", "Base45"),
            }
        },
ToBase58:({Dot})=>{
            return {
                        optName: Dot("M3qytc", "Encode {0}", "Base58"),
            }
        },
ToBase62:({Dot})=>{
            return {
                        optName: Dot("M3ytc", "Encode {0}", "Base62"),
            }
        },
ToBase64:({Dot})=>{
            return {
                  optName: Dot("M3ytc", "Encode {0}", "Base64"),
            }
        },
ToBase85:({Dot})=>{
            return {
                        optName: Dot("M3ytc", "Encode {0}", "Base85"),
            }
        },
ToBCD:({Dot})=>{
            return {
                  optName: "To BCD",
            }
        },
ToHex:({Dot})=>{
            return {
                  optName: "To Hex",
            }
        },
XMLBeautify:({Dot})=>{
            return {
                        optName: Dot("yMZW-GEgf", "Format XML"),
            }
        },
XMLMinify:({Dot})=>{
            return {
                  optName: Dot("yMZW-GEgf", "Format XML"),
            }
        },
YAMLBeautify:({Dot})=>{
            return {
                  optName: Dot("yaml.format.btn", "Format YAML"),
            }
        }
    }
export type AppOpFnMapTypeKeys = keyof typeof AppOptFnMap;
    
    