 // DO NOT TOUCH THIS FILE, AUTO GENERATED BY SYSTEM
//    Copyright
    import {AppOpFnMapType} from './d_meta';
    
   export  let AppOptFnMap:AppOpFnMapType ={
CSSBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("Ol1ZcWomT", "{0} Beautify", "CSS"),
            optDescription: Dot(
                "md2aO2NaJITm",
                "Indents and prettifies Cascading Style Sheets (CSS) code, making it easier to read and understand.",
            ),
            }
        },
CSSMinify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("-nL_B5PoN", "Compresses {0}", "CSS"),
      optDescription: Dot(
        "Y__Zb1_4Q",
        "Minifies Cascading Style Sheets (CSS) code, removing all unnecessary characters."
      ),
            }
        },
CSVToJSON:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("tZINaUR4b", "CSV to JSON"),
      optDescription: Dot("raTAuBwBz", "Converts a CSV file to JSON format."),
            }
        },
FromBase32:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("rVdu", "Decode {0}", "Base32"),
            optDescription: Dot(
                "JiUE8",
                "This operation decodes data from an ASCII {0} string back into its raw format.",
                "Base32"
            ),
            }
        },
FromBase45:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("rVqlu", "Decode {0}", "Base45"),
            optDescription: Dot(
                "JiUE8",
                "This operation decodes data from an ASCII {0} string back into its raw format.",
                "Base45"
            ),
            }
        },
FromBase58:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("L9qbQku", "Decode {0}", "Base58"),
            optDescription: Dot(
                "JdqidUE8",
                "This operation decodes data from an ASCII string (with an alphabet of your choosing, presets included) back into its raw form.",
            ),
            }
        },
FromBase62:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("L9bQku", "Decode {0}", "Base62"),
            optDescription: Dot(
                "JdqiUE8",
                "This operation decodes data from an ASCII string (with an alphabet of your choosing, presets included) back into its raw form.",
            ),
            }
        },
FromBase64:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("rVqlu", "Decode {0}", "Base64"),
      optDescription: Dot(
        "1k_44",
        "This operation decodes data from an ASCII Base64 string back into its raw format.",
      ),
            }
        },
FromBase85:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("rVqlu", "Decode {0}", "Base85"),
            optDescription: Dot(
                "wj3VS",
                "This operation decodes data from an ASCII {0} string back into its raw format.",
                "Base85"
            ),
            }
        },
FromBCD:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("iLYwoR0xe", "From {0}", "BCD"),
      optDescription: Dot("0YKce", "Converts a Binary-Coded Decimal (BCD) string to a decimal number."),
            }
        },
FromHex:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("5RPdtVff3", "From Hex"),
            }
        },
GenericCodeBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("generic-NI-UFPTe0", "Beautify Generic Code"),
            optDescription: Dot(
                "generic-code-beautify.desc.2b3c",
                "This operation formats code in various programming languages to improve readability by applying consistent indentation, line breaks, and adhering to language-specific style guidelines.",
                ""
            ),
            }
        },
HTMLBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("yMZW-figFKwrYO", "Format {0}", "HTML"),
            optDescription: Dot(
                "html-beautify.desc.2a5f9",
                "Beautifies the input XML by adding indentation and line breaks to make it easier to read."
            ),
            }
        },
JavaScriptBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("6UICxHzVR.name", "Beautify {0}", "JavaScript"),
            optDescription: Dot(
                "WFUWzv_px",
                "Parses and pretty prints valid JavaScript code. Also works with JavaScript Object Notation (JSON).",
            ),
            }
        },
JavaScriptMinify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("e3WgQaZlb", "Compresses {0}", "JavaScript"),
      optDescription: Dot(
        "ojCWEFdVe",
        "Compresses JavaScript code, removing all unnecessary characters.",
      ),
            }
        },
JSONBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("json-beautify.text.93kq", "Beautify JSON Data"),
            optDescription: Dot(
                "json-beautify.desc.0912",
                "This operation formats JSON data to improve readability by adding proper indentation, line breaks, and sorting keys consistently.",
            ),
            }
        },
JSONMinify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("meeMC1Uk7.text.93kq", "Minify {0}", "JSON"),
      optDescription: Dot(
        "EO6Qv5dCA",
        "Minifies JSON code, reduce the bundle size of your JSON code."
      ),
            }
        },
MD2:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("md2.text.192d3", "Generate {0} Hash", "MD2"),
      optDescription: Dot(
        "md2.desc.1039",
        "This operation hashes data into an {0} hash.",
        "MD2"
      ),
            }
        },
MD4:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("md4.text.192d3", "Generate {0} Hash", "MD4"),
      optDescription: Dot(
        "md4.desc.1039",
        "This operation hashes data into an {0} hash.",
        "MD4"
      ),
            }
        },
MD5:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("md5.textiDjMIo", "Generate {0} Hash", "MD5"),
      optDescription: Dot(
        "md5.desc.rxsHq",
        "This operation hashes data into an {0} hash.",
        "MD5"
      ),
            }
        },
MD6:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("md6.text.192d3", "Generate {0} Hash", "MD6"),
      optDescription: Dot(
        "md6.desc.1039",
        "This operation hashes data into an {0} hash.",
        "MD6"
      ),
            }
        },
RemoveLineNumbers:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("OrCD8PqwH", "Remove line numbers"),
      optDescription: Dot("Vc40-vfod", "Removes line numbers from the output if they can be trivially detected."),
            }
        },
RemoveWhitespace:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("U-SKci0LP", "Remove whitespace"),
      optDescription: Dot("8hlgTVznY", "Optionally removes all spaces, carriage returns, line feeds, tabs and form feeds from the input data.<br><br>This operation also supports the removal of full stops which are sometimes used to represent non-printable bytes in ASCII output."),
            }
        },
Reverse:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("f7Fp-L9V-", "Reverse"),
      optDescription: Dot("wmuD_KXJ2", "Reverses the input string."),
            }
        },
SHA0:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: "SHA0",
            }
        },
SHA1:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: "SHA1",
            }
        },
SHA2:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: "SHA2",
            }
        },
SHA3:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: "SHA3",
            }
        },
SQLBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("json-beautify.name.0912", "Format SQL"),
            optDescription: Dot(
                "rE6fUsSGl",
                "Indents and prettifies Structured Query Language (SQL) code."
            ),
            }
        },
SQLMinify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("6wdtJ4vmg.name.0912", "Minify {0}", "SQL"),
      optDescription: Dot(
        "LxaEFHbfa",
        "Minifies SQL code, reduce the bundle size of your SQL code.",
      ),
            }
        },
Tail:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optDescription: Dot("2Va7Txc-V", "Like the UNIX tail utility.<br>Gets the last n lines.<br>Optionally you can select all lines after line n by entering a negative value for n.<br>The delimiter can be changed so that instead of lines, fields (i.e. commas) are selected instead."),
      optName: Dot("y46w7Q9TH", "Tail"),
            }
        },
ToBase32:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("M3ytc", "Encode {0}", "Base32"),
            optDescription: Dot(
                "BGd7dP9",
                "This operation encodes raw data into an ASCII {0} string.",
                "Base32"
            ),
            }
        },
ToBase45:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("M3ytc", "Encode {0}", "Base45"),
            optDescription: Dot(
                "BGd7dP9",
                "This operation encodes raw data into an ASCII {0} string.",
                "Base45"
            ),
            }
        },
ToBase58:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("M3qytc", "Encode {0}", "Base58"),
            optDescription: Dot(
                "BGdd7dP9",
                "This operation encodes raw data into an ASCII {0} string.",
                "Base58"
            ),
            }
        },
ToBase62:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("M3ytc", "Encode {0}", "Base62"),
            optDescription: Dot(
                "BGd7dP9",
                "This operation encodes raw data into an ASCII {0} string.",
                "Base62"
            ),
            }
        },
ToBase64:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("M3ytc", "Encode {0}", "Base64"),
      optDescription: Dot(
        "BGd7P9",
        "This operation encodes raw data into an ASCII Base64 string.",
      ),
            }
        },
ToBase85:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("M3ytc", "Encode {0}", "Base85"),
            optDescription: Dot(
                "nodBw",
                "This operation encodes raw data into an ASCII {0} string.",
                "Base85"
            ),
            }
        },
ToBCD:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: "To BCD",
      optDescription: Dot("98KcL", "Converts a decimal number to Binary-Coded Decimal (BCD)."),
            }
        },
ToHex:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("rZL0xuQu2", "To Hex"),
            }
        },
XMLBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                        optName: Dot("yMZW-GEgf", "Format XML"),
            optDescription: Dot(
                "xml-beautify.desc.2a5f9",
                "This operation formats XML data to improve readability by adding proper indentation, line breaks, and ensuring well-formed structure.",
                ""
            ),
            }
        },
XMLMinify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("yMZW-GEgf", "Format XML"),
      optDescription: Dot(
        "xml-bdeautify.desc.2a5f9",
        "Minify XML Code"
      ),
            }
        },
YAMLBeautify:({Dot})=>{
            return {
                // DO NOT CHANGE THIS PART AS THIS WHOLE FILE IS GENERATED BY SYSTEM
                  optName: Dot("yaml.format.btn", "Format YAML"),
      optDescription: Dot(
        "yaml-beautify.desc.2a5f9",
        "This operation formats YAML data to improve readability by adding proper indentation, line breaks, and ensuring well-formed structure.",
        ""
      ),
            }
        }
    }
export type AppOpFnMapTypeKeys = keyof typeof AppOptFnMap;
    
    