// LafTools - The Leading All-In-One ToolBox for Programmers.
// 
// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf 
// Description: 
// Copyright (C) 2024 - Present, https://laf-tools.com and https://codegen.cc
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
import CSSBeautify from "../../operations/CSSBeautify.mjs";
import CSSMinify from "../../operations/CSSMinify.mjs";
import CSSSelector from "../../operations/CSSSelector.mjs";
import FromMessagePack from "../../operations/FromMessagePack.mjs";
import GenericCodeBeautify from "../../operations/GenericCodeBeautify.mjs";
import JPathExpression from "../../operations/JPathExpression.mjs";
import JSONBeautify from "../../operations/JSONBeautify.mjs";
import JSONMinify from "../../operations/JSONMinify.mjs";
import JavaScriptBeautify from "../../operations/JavaScriptBeautify.mjs";
import JavaScriptMinify from "../../operations/JavaScriptMinify.mjs";
import JavaScriptParser from "../../operations/JavaScriptParser.mjs";
import RenderMarkdown from "../../operations/RenderMarkdown.mjs";
import SQLBeautify from "../../operations/SQLBeautify.mjs";
import SQLMinify from "../../operations/SQLMinify.mjs";
import SyntaxHighlighter from "../../operations/SyntaxHighlighter.mjs";
import ToCamelCase from "../../operations/ToCamelCase.mjs";
import ToKebabCase from "../../operations/ToKebabCase.mjs";
import ToMessagePack from "../../operations/ToMessagePack.mjs";
import ToSnakeCase from "../../operations/ToSnakeCase.mjs";
import XMLBeautify from "../../operations/XMLBeautify.mjs";
import XMLMinify from "../../operations/XMLMinify.mjs";
import XPathExpression from "../../operations/XPathExpression.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Code = {
    "CSS Beautify": CSSBeautify,
    "CSS Minify": CSSMinify,
    "CSS selector": CSSSelector,
    "From MessagePack": FromMessagePack,
    "Generic Code Beautify": GenericCodeBeautify,
    "JPath expression": JPathExpression,
    "JSON Beautify": JSONBeautify,
    "JSON Minify": JSONMinify,
    "JavaScript Beautify": JavaScriptBeautify,
    "JavaScript Minify": JavaScriptMinify,
    "JavaScript Parser": JavaScriptParser,
    "Render Markdown": RenderMarkdown,
    "SQL Beautify": SQLBeautify,
    "SQL Minify": SQLMinify,
    "Syntax highlighter": SyntaxHighlighter,
    "To Camel case": ToCamelCase,
    "To Kebab case": ToKebabCase,
    "To MessagePack": ToMessagePack,
    "To Snake case": ToSnakeCase,
    "XML Beautify": XMLBeautify,
    "XML Minify": XMLMinify,
    "XPath expression": XPathExpression,
};

export default OpModules;
