// LafTools - The Leading All-In-One ToolBox for Programmers.
// 
// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf 
// Description: 
// Copyright (C) 2024 - Present, https://laf-tools.com and https://codegen.cc
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
import Bzip2Compress from "../../operations/Bzip2Compress.mjs";
import Bzip2Decompress from "../../operations/Bzip2Decompress.mjs";
import Gunzip from "../../operations/Gunzip.mjs";
import Gzip from "../../operations/Gzip.mjs";
import LZ4Compress from "../../operations/LZ4Compress.mjs";
import LZ4Decompress from "../../operations/LZ4Decompress.mjs";
import LZMACompress from "../../operations/LZMACompress.mjs";
import LZMADecompress from "../../operations/LZMADecompress.mjs";
import LZStringCompress from "../../operations/LZStringCompress.mjs";
import LZStringDecompress from "../../operations/LZStringDecompress.mjs";
import RawDeflate from "../../operations/RawDeflate.mjs";
import RawInflate from "../../operations/RawInflate.mjs";
import Tar from "../../operations/Tar.mjs";
import Untar from "../../operations/Untar.mjs";
import Unzip from "../../operations/Unzip.mjs";
import Zip from "../../operations/Zip.mjs";
import ZlibDeflate from "../../operations/ZlibDeflate.mjs";
import ZlibInflate from "../../operations/ZlibInflate.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Compression = {
    "Bzip2 Compress": Bzip2Compress,
    "Bzip2 Decompress": Bzip2Decompress,
    "Gunzip": Gunzip,
    "Gzip": Gzip,
    "LZ4 Compress": LZ4Compress,
    "LZ4 Decompress": LZ4Decompress,
    "LZMA Compress": LZMACompress,
    "LZMA Decompress": LZMADecompress,
    "LZString Compress": LZStringCompress,
    "LZString Decompress": LZStringDecompress,
    "Raw Deflate": RawDeflate,
    "Raw Inflate": RawInflate,
    "Tar": Tar,
    "Untar": Untar,
    "Unzip": Unzip,
    "Zip": Zip,
    "Zlib Deflate": ZlibDeflate,
    "Zlib Inflate": ZlibInflate,
};

export default OpModules;
