// LafTools - The Leading All-In-One ToolBox for Programmers.
// 
// Date: Sun, 14 Jan 2024
// Author: Ryan Laf <get>
// Description: 
// Copyright (C) 2024 - Present, https://laf-tools.com and https://codegen.cc
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
import ExtractDates from "../../operations/ExtractDates.mjs";
import ExtractDomains from "../../operations/ExtractDomains.mjs";
import ExtractEmailAddresses from "../../operations/ExtractEmailAddresses.mjs";
import ExtractFilePaths from "../../operations/ExtractFilePaths.mjs";
import ExtractIPAddresses from "../../operations/ExtractIPAddresses.mjs";
import ExtractMACAddresses from "../../operations/ExtractMACAddresses.mjs";
import ExtractURLs from "../../operations/ExtractURLs.mjs";
import Filter from "../../operations/Filter.mjs";
import FindReplace from "../../operations/FindReplace.mjs";
import Register from "../../operations/Register.mjs";
import RegularExpression from "../../operations/RegularExpression.mjs";
import Strings from "../../operations/Strings.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Regex = {
    "Extract dates": ExtractDates,
    "Extract domains": ExtractDomains,
    "Extract email addresses": ExtractEmailAddresses,
    "Extract file paths": ExtractFilePaths,
    "Extract IP addresses": ExtractIPAddresses,
    "Extract MAC addresses": ExtractMACAddresses,
    "Extract URLs": ExtractURLs,
    "Filter": Filter,
    "Find / Replace": FindReplace,
    "Register": Register,
    "Regular expression": RegularExpression,
    "Strings": Strings,
};

export default OpModules;
